# **Лабораторна робота №2А**
---
## Послідовність виконання лабораторної роботи:
#### 1. Переглянув офіційну документацію для ***Python***.
#### 2. Створюю файл ***test.py*** для виконання базових прикладів.
1. Виводжу вбудованні константи за допомогою команд:

    ```python
    print("Перша константа: ", True)
    print("Друга константа: ", False)
    print("Третя константа: ", NotImplemented)
    ```
1. Виводжу результат роботи вбудованих функцій за допомогою команд:
   ```python
    print("Число 20 в 16-ві системі числення дорівнює: ", hex(20))
    print("2 в 10 степені дорівнює: ", pow(2,10))
    print("Максимальне число з чисел 5,6,9,3,45 :",max(5,6,9,3,45))
    ```
1. Виводжу результат роботи циклу і розгалужень за допомогою команд:
    ```python
    x= [1 for i in range(10)]
    print("Виведення 10 одиниць з масиву: ",x)
    b=5
    print("Змінна B дорівнює 5" if b == 5 else "Змінна B не дорівнює 5")
    ```
1. Виводжу результат роботи конструкції `try`->`except`->`finally` при помилці за допомогою команд:
    ```python
    y=[5,2]
    print("Що буде якщо вивести 10 елемент масиву y[]?: ")
    try:
        print(y[10])
    except Exception as e:
        print(e)
    finally:
        print("То ось що буде!")
    ```
1. Виводжу результат роботи контекст-менеджера `with` за допомогою команд:
    ```python
    i=1
    with open("README.md", "r") as file:
        for line in file:
            print("Рядок " + str(i) + ": " + line)
            i=i+1
    ```
1. Виводжу результат роботи з `lambdas` за допомогою команд:
    ```python
    new_lambda = lambda first_number, second_number: f'Сума першого і другого числа дорівнює {first_number + second_number}'
    print("Розташування функції в памяті: ", new_lambda)
    print("Виклик лямбди: ", new_lambda(5, 6))
    ```
#### 3. Створив у власному рипозеторії такі файли:
   ```text
   L2a/
   ├── modules/
   │   └── common.py
   ├── __init__.py
   └── __main__.py
   ```
1. Перейшовши у папку з даними файлами запустив виконання програми цією командою:

    ```sh
    python3 .
    ```
    Виконання команди:
```text
l1@l1:~/TPIS/IK_31/L2a$ python3 .
We are in the __main__
2021-12-04 14:06:40.215498
linux
test
```
1. Після запуску команди `python3 .` програма в першому рядку виводить назву файла який виконувався, в другому рядку виводиться час і дата виконання даної програми, в третьому рядку виводиться ос на якій було запущено програму і в четвертому рядку виведено текст "test".

    a. Після запуску команди: `python3 . -h` в консоль виводиться інформація про додаткові параметри та їх використання. Результат виконання команди:
```text
l1@l1:~/TPIS/IK_31/L2a$ python3 . -h
usage: . [-h] [-o OPT] [-l]

Приклад передачі аргументів у Python програму.

optional arguments:
  -h, --help            show this help message and exit
  -o OPT, --optional OPT
                        Цей параметр є вибірковим.
  -l, --logs            Якщо виконати команду з цим параметром будуть
                        виводитись логи.

```
    
    b. Після запуску команди: `python3 . -o "Цей текст також має вивестись"` в консоль виводиться інформація така сама як і в пункті 2. тільки додається текст про те що з консолї було передано аргумент і саме повідомлення яке ми передаємо. Результат виконання команди:
```text
l1@l1:~/TPIS/IK_31/L2a$ python3 . -o "Цей текст також має вивестись"
We are in the __main__
2021-12-04 14:11:27.737270
linux
З консолі було передано аргумент
 ========== >> Цей текст також має вивестись << ==========
test

```
    c. Дитально ознайомився з аргументами.
    d. Ознайомився з логуванням і запустив команду `python3 . --logs`.
    Результат виконання команди:
```text
l1@l1:~/TPIS/IK_31/L2a$ python3 . --logs
2021-12-04 14:12:20,249 root INFO: Тут буде просто інформативне повідомлення
2021-12-04 14:12:20,249 root WARNING: Це Warning повідомлення
2021-12-04 14:12:20,250 root ERROR: Це повідомлення про помилку
test

```
1. Створив власну функцію у файлі `common.py` яка буде виводить всі парні числа від 0 до 100,  якщо у функцію передати значення True і непарні якщо значення False. Виклик цієї функцію виконую з `__main__` .
Код власної функції:
```python
    def filtr_number(filtr):
        numbers=range(0,101)
        if filtr=="True":
    	    msg = "Парні елементи: " 
        elif filtr=="False":
    	    msg = "Непарні елементи: "
    	    
        for num in numbers:
        	if (filtr == "True") & (num%2 == 0):
        	    msg += str(num) + " "
        	elif (filtr == "False") & (num%2 != 0):
        	    msg += str(num) + " "
        return msg
```
    Результат виконання з параметром `-o True`:
```text
l1@l1:~/TPIS/IK_31/L2a$ python3 . -o True
We are in the __main__
2021-12-04 14:15:41.445465
linux
Парні елементи: 0 2 4 6 8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94 96 98 100 
З консолі було передано аргумент
 ========== >> True << ==========
test

```
    Результат виконання з параметром `-o False`:
```text
l1@l1:~/TPIS/IK_31/L2a$ python3 . -o False
We are in the __main__
2021-12-04 14:16:19.213996
linux
Непарні елементи: 1 3 5 7 9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95 97 99 
З консолі було передано аргумент
 ========== >> False << ==========
test

```
1. Створив функцію яка може виконуватись з помилкою. У випадку її виникнення виводить `ERROR` повідомлення за допомогою логування використовуючи бібліотеку `logging`. Якщо функція виконалася без помилки то виводить `INFO` повідомлення.
Код власної функції:
```python
    def view_array():
        x=[5,9,6,3]
        print("Масив X[]:", x)
        index = int(input("Введіть номер елемента масиву який хочете вивести: "))
        try:
        	print(f"X[{index}] = {x[index]}")
        except IndexError:
            logging.error("Ви ввели число за межами проміжку 0-3")
        else:
        	logging.info("Ви ввели коректні дані")
```
    Результат виконання з помилкою:
```text
l1@l1:~/TPIS/IK_31/L2a$ python3 .
We are in the __main__
2021-12-04 14:17:45.540042
linux
Масив X[]: [5, 9, 6, 3]
Введіть номер елемента масиву який хочете вивести: 7
2021-12-04 14:17:57,871 root ERROR: Ви ввели число за межами проміжку 0-3
test

```
    Результат виконання без помилки:
```text
l1@l1:~/TPIS/IK_31/L2a$ python3 .
We are in the __main__
2021-12-04 14:18:53.151294
linux
Масив X[]: [5, 9, 6, 3]
Введіть номер елемента масиву який хочете вивести: 2
X[2] = 6
2021-12-04 14:19:00,335 root INFO: Ви ввели коректні дані
test

```

